### ISSUE TITLE
Bug in inc\connect.php

### ISSUE THREAD

**Issue by tutunciyan** [seehase/ZonPHP#1]
When weewx is not used, the code fails. Below is an updated version that fixes the issue.
```php
<?php
ob_start();
$con = mysqli_connect($sserver, $susername, $spassword, $sdatabase_name);

if (!$con) {
	die(header('location:install/opstart_installatie.php?fout=connect'));
}

if ($use_weewx == true)
{
	$con_weewx = mysqli_connect($weewx_server, $weewx_username, $weewx_password, $weewx_database_name);

	if (!$con_weewx) {
		die(header('location:install/opstart_installatie.php?fout=connect'));
	}	
}

ob_end_flush();
?>
```

**Comment by seehase** [comment]
I think this is not the issue... but you are right there is a bug

If you do not use weewx than set it to false in the Parameter.php file
```PHP
$use_weewx = false;
```
the correct code must be like this 
```PHP
if ($use_weewx == true)
{
	$con_weewx = mysqli_connect($weewx_server, $weewx_username, $weewx_password, $weewx_database_name);

	if (!$con_weewx) {
		die(header('location:install/opstart_installatie.php?fout=connect'));
	}	
}
```
I will fix it this evening

**Comment by seehase** [comment]
I fixed the gub in both branches

**Comment by tutunciyan** [comment]
Ok, but you still haven't fixed the actual bug :-)
You should move the check on $con_weewx into the if branch where the connection is initialized, just like the code above.

**Comment by seehase** [comment]
The weewx connection is only established when 
if ($use_weewx == true)

in case you configured to use weewx and there is connection issue e.g. wrong host or password
then this code
if (!$con_weewx) {
		die(header('location:install/opstart_installatie.php?fout=connect'));
	}	
should redirect to the config page

in case you don't use weewx nothing will happens

**Comment by seehase** [comment]
sorry my fault, now it should be fixed

**Comment by tutunciyan** [comment]
I'm a c# developer, so don't know much about php. But I'm able to read an simple if statement :-)
Try to set your own use_weewx setting to false.

**Comment by tutunciyan** [comment]
Cool!

**Comment by seehase** [comment]
I'm a JAVA developer and PHP in my free time
i'm not very familla with git so far... so I'm still learning
