### ISSUE TITLE
type error/mistake 'avarage' in various charts

### ISSUE THREAD

**Issue by ghost** [seehase/ZonPHP#13]
See in chart of build 2018.11.04 a type-error has been noticed.

Actual result: 'av**a**rage' 
Expected result: 'av**e**rage'

Found in various charts:

1. chart 'overview last 5 years' 
2. chart 'weekly overview' 
3. chart 'monthly overview'
4. chart 'annual / yearly overview' 
5. chart 'all years overview'

See some screenshots attached, with orange box/color highlighted areas of noticed issue.
![schermafbeelding 2018-11-11 om 11 17 10](https://user-images.githubusercontent.com/44602962/48311660-7cbd2280-e5a3-11e8-90ee-2a5a791d59a8.png)

![schermafbeelding 2018-11-11 om 11 20 19](https://user-images.githubusercontent.com/44602962/48311685-d9b8d880-e5a3-11e8-9c83-39caf61d572e.png)

**Comment by seehase** [comment]
fixed it in Version build 2018.11.05
please clear sesseion afer installing new Version

**Comment by seehase** [comment]
replaced all occurrences of avarage with average, so it should be fixed

**Comment by ghost** [comment]
retested in build 2018.11.05, Passed! defect may be closed.
