### ISSUE TITLE
Enhance day view to show more than one invertert at once

### ISSUE THREAD

**Issue by seehase** [seehase/ZonPHP#18]
As proposal from Eric, we can change day chart to show all inverter in one view with posiblitiy to swicht between converters

![grafik](https://user-images.githubusercontent.com/3663078/54035778-607c6b80-41ba-11e9-9ec0-388ecf14a22e.png)
the chart is additiv

**Comment by ericplan** [comment]
Have a working demo on http://www.e2fb.nl/zphp/day_twee.php. All work is done in the daycharts file (line 238 - 253). Output from the loop is strict JSON and can be passed directly to JS. But I have to work on the correct data for the selection (also on the max and cumulative lines). Also work on creating the javascript variables for every inverter in a for loop and add them to the Highcharts graph automatically. For now I created them by hand.

**Comment by seehase** [comment]
Can you attach the code of your working sample, then I try to integrate it

**Comment by ericplan** [comment]
Hi Holger,

Here you are. Be extremely careful with the foreach output. Hard to get it strict JSON, but it pays off because you can use it immediately in the Highcharts series.

Regards,

Eric

**Comment by ericplan** [comment]
Since this implemented in the new development build and after some thinking about it, why not implement the "max"- and "cum" line 'stacked' as well? Should be nice.

**Comment by seehase** [comment]
Finished day view, continue working also an month/year and all year charts ... stay tuned

**Comment by seehase** [comment]
added multiview for months as well, year overview will follow

**Comment by seehase** [comment]
Already done
