### ISSUE TITLE
Enhance tooltip by leaving out day and date

### ISSUE THREAD

**Issue by ericplan** [seehase/ZonPHP#19]
The tooltip on the days overview page contains day of the week, date, month and year. No need for, because this is written in big capitals on the page header. The only meaningful part is the time.

Furthermore the production in the tooltip is shown in Wh. kWh is a better unit and there is only need for 1 decimal. This reduces the number of digits.

Both things improve the readability on smaller screens like smartphones.

**Comment by seehase** [comment]
Fixed it, datetime format can noe be configured in the parameter and cum-line in kWh
