### ISSUE TITLE
multiple inverters - day view - differentiate / use more colours

### ISSUE THREAD

**Issue by ghost** [seehase/ZonPHP#20]
when a day-view is selected, with multiple inverters, there's one coloured area visible with the sum of the 'n' inverters. Would be nice to have (in case of 3 inverters/systems), 3 shades of color visible to differentiate more clearly. Is this possible?
I use currently the Development version v2018.11.14.

**Comment by seehausen** [comment]
Hi Niels
I already worked on this, see
https://solar.seehausen.org/day_overview.php?type=all

I checked in the code on sunday, but did not increased the build number so far
please checkout the lates development branch, and I would like to get your feedback

Currently I have to change the max line and cum line according to all inverter

**Comment by ghost** [comment]
downloaded dev-version 2018.11.15 and installed. indeed now multi-inverter show separate colors. Thanks. Issue can be closed.

**Comment by seehase** [comment]
Will be fixed with [Issus#18]
