### ISSUE TITLE
Enable full screen mode on ios

### ISSUE THREAD

**Issue by ericplan** [seehase/ZonPHP#21]
IPhone and iPad are capable of running in full screen mode by adding a simple meta tag in the page header `<meta name="apple-mobile-web-app-capable" content="yes">`

This can be placed in the header.php. The result is shown in the pictures
![0227717E-CFDB-48C4-8D1B-236D73172B85](https://user-images.githubusercontent.com/48489161/54679187-f1324000-4b06-11e9-9457-94c72743aa72.png)
![266F4A87-59FF-488E-8CB3-A8DE5D9733D5](https://user-images.githubusercontent.com/48489161/54679188-f1324000-4b06-11e9-889a-9de5056361a6.png)

**Comment by seehausen** [comment]
Hi Eric
can you discribe the metatag which has to be set? then I can add that

**Comment by ericplan** [comment]
I added it to the message, for some reason it disappeared after inserting the pics.
Code was not shown in message, corrected this in the original message.

**Comment by ericplan** [comment]
`<meta name="apple-mobile-web-app-capable" content="yes">`

**Comment by seehase** [comment]
I commit and pushed the change to the header.php
can you checkout latest dev branch and check? I can test the results this evening too.

**Comment by ericplan** [comment]
It is in the same place where i putted it, so i guess it works. 

BTW There is a typo in the word “monitoring” on line 18

**Comment by seehase** [comment]
typo fixed
