### ISSUE TITLE
Incorrect kWhp in subtitle day_overview

### ISSUE THREAD

**Issue by ericplan** [seehase/ZonPHP#23]
There is a typo in line 342 in the day_chart.php. Divided by 1000 should be removed. I only dream of this values :)

Furthermore  comparing in a percentage to the reference **month** (line 343) is not very useful. I should leave it out for the sake of a clear subtitle.

**Comment by seehase** [comment]
Hi Eric
I fixed the calculation and removed % value
Please check if is correct now, and have also a look on month/year view
