### ISSUE TITLE
Diary / Tagebuch in Developer layout issue

### ISSUE THREAD

**Issue by ghost** [seehase/ZonPHP#25]
![tagebuch zonphp7](https://user-images.githubusercontent.com/44602962/55952569-37884400-5c5a-11e9-8953-76fc0d198570.PNG)

Diary or events registered in tagebuch.txt (with HTML markup) are shown on screen with incorrect layout. Fix needed (most likely) in file mydiary.php.

Detected since v2018.11.15 (dev)

**Comment by seehausen** [comment]
@nthijssen  Can you upload your tagebuch.txt for testing please?

**Comment by seehase** [comment]
HI @nthijssen 
I fixed the mydiary in v2019.03.13 (dev)
please checkout latest dev branch and provide feedback  (only mydiary.php was changed ... and versioninfo"

Kind regards
Holger

**Comment by ghost** [comment]
[tagebuch.txt](https://github.com/seehase/ZonPHP/files/3075991/tagebuch.txt)
see attached tagebuch.txt as requested.

**Comment by ghost** [comment]
Tested on/with build 2018.11.15 (dev), this issue is now solved. Retest: passed.
