### ISSUE TITLE
undefined chart_date_format error on build 2019.03.13 (dev) 

### ISSUE THREAD

**Issue by ghost** [seehase/ZonPHP#26]
when updating for retest issue on tagebuch.txt, I did notice this issue (see screenshot):
![Schermafbeelding 2019-04-13 om 10 53 20](https://user-images.githubusercontent.com/44602962/56077273-89f06e80-5dda-11e9-91ee-58e0b4f5c85b.png)

after starting up Zonphp, sleecting an inverter (on day-view), it's visible.

**Comment by seehase** [comment]
fixed with v2019.03.15 (dev)
and moved "diary" to info menu

This is a temporary problem by introducing a new variable and cache was not refreshed.

File changed load_cache and menu
