### ISSUE TITLE
multi inverter chart 'all years overview' not working

### ISSUE THREAD

**Issue by ghost** [seehase/ZonPHP#5]
As I have multiple inverters logging onto ZonPHP, this issue shows up:
When having installed latest version (v2018.01.04), I open from main screen the chart 'All years overview' (left column, third chart from the top).

**As actual result,** the chart shows all years, but from ALL inverters, while 1 inverter(name) has been selected.

**As expected result**, the chart should show all years from selected inverter (visible in top of the screen of ZonPHP).
Switching between inverter / all inverters buttons won't solve it. Possibly an issue in query part.

**Comment by seehausen** [comment]
did you checked the current development version v2018.06.02
https://github.com/seehase/ZonPHP/archive/development.zip

I did some changes. Please have a look if your issue is still there

**Comment by ghost** [comment]
I did download your development set, and installed it. Sadly, also in v2018.06.02 it is still having the same issue.

**Comment by seehase** [comment]
Hi Niels
I'm not sure that I understand the bug, can you send me some screenshots
and is you website available in the internet (you can send me a private mail to zonphp@seehausen.org)

Can you reproduce the bug on my site https://solar.seehausen.org I also have 2 inverters

Please provide me some more information, then I try to fix it
Kind Regards
Holger

**Comment by ghost** [comment]
my websites are available on internet:
the zonphp 2.25 ('original'): https://www.renewable-energy-now.org/zonphp
the build 2018.06.02 : https://www.renewable-energy-now.org/zonphp71
the build 2018.01.04 : https://www.renewable-energy-now.org/zonphp7

All use the same database & data to show charts.

**Comment by seehase** [comment]
but the 
https://www.renewable-energy-now.org/zonphp7/all_years_overview.php?naam=JIANGSUKINGSUN
looks different as
https://www.renewable-energy-now.org/zonphp7/all_years_overview.php?naam=SUNTECH

I don't see the problem

**Comment by ghost** [comment]
![schermafbeelding 2018-11-04 om 19 38 58](https://user-images.githubusercontent.com/44602962/47968377-74c42680-e069-11e8-888d-a85943bae518.png)
Above an overview of inverter/system MSK, of all years showing in ZonPHP v2.25 version.

But in the development version (v2018.06.05) just downloaded, this chart can't be reproduced (yet):
For MSK selected system it shows (despite toggling between inverter/all inverters):
![schermafbeelding 2018-11-04 om 19 41 42](https://user-images.githubusercontent.com/44602962/47968401-be147600-e069-11e8-8536-3e19a26a5141.png)

**Comment by seehase** [comment]
OK, I see the problem 
I will have a look

**Comment by seehase** [comment]
Hi @nthijssen 
I think I solved the problem 
please install current developer version and provide feedback if problem still exists

**Comment by ghost** [comment]
Tested on build 2018.11.04 and it works now! Pass!

Niels Thijssen
nielsthijssen75@gmail.com <mailto:nielsthijssen75@gmail.com>

My OpenPGP key is: 75FD3735
