### ISSUE TITLE
incorrect notation of Unit of Measurement : kWhp instead of kWh/kWp or Wh/Wp

### ISSUE THREAD

**Issue by ghost** [seehase/ZonPHP#6]
build: v2018.06.02
Chart found: opening screen, monthly overview;
but also chart all year overview (noting: kWh instead of kWh/kWp)

**Expected**: correct notation of Wh/Wp or kWh/kWp as Unit of Measurement.
**Actual**: incorrect notation of kWhp or nothing at all.

**Comment by seehase** [comment]
Hi Niels
I tried to fix the units... I'm not an expert in solar metrics so if you see some other issues please let me know... If you can send me screenshots of what is wrong and how it should look like that would help me much

mailto: zonphp@seehausen.org
Kind regards
Holger

please check current developer branch
https://github.com/seehase/ZonPHP/archive/development.zip
