### ISSUE TITLE
Homepage not refreshing after import on first load.

### ISSUE THREAD

**Issue by wimmme** [seehase/ZonPHP#77]
Hi, this is not a real issue; just something that worked in previous versions and now it doesn't.

After first load of the homepage, where ZonPHP loads the files and does the import in the database, the day_overview card is empty.
After a refresh of the page the chart is there. I think in previous versions it did a refresh after that load. 

Also very well possible I did that myself. I was still running a version of early 2018 , and made the mistake of starting to tweak change wherever necessary or desired without documenting or sourcecontrolling it ;-)
Made the the move/merge back to the official version, but that was not without pain, migrations, manual sql, and some mods.
Especially the importer file. I still use ( a now updated) version of the old Invullen_gegevens_solarlogXomvormjs.php, because the solarlog version doesn't work for me.

Anyways, might be a good suggestionto refresh the page after loading import data ....

**Comment by seehausen** [comment]
@wimmme 
I can confirm this "Bug" I also noticed it. I optimised the importing in a bad way :-(
I will check and fix it

**Comment by seehausen** [comment]
@wimmme 
I hope I fixed the bug... can you check latest version 3.1.1 and close issue if solved?

**Comment by wimmme** [comment]
Yep, fixed ! Tnx a lot !
